MODULE_NAME := avpu
OUT := $(MODULE_NAME)

AVPU_NO_DMABUF ?= 0

SRCS := \
  avpu_main.c \
  avpu_ip.c \
  avpu_alloc.c \
  avpu_alloc_ioctl.c \

ifeq ($(AVPU_NO_DMABUF),1)
SRCS += \
  avpu_no_dmabuf.c
else
SRCS += \
  avpu_dmabuf.c
endif

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

# Include headers from t31 subdirectory
ccflags-y += -I$(src)/t31
